/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package facebookfinal;

import facebook4j.FacebookException;
import facebook4j.FacebookFactory;
import facebook4j.conf.ConfigurationBuilder;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author Aaron
 */
public class MetodosYMenu extends javax.swing.JFrame {

    /**
     * Creates new form MetodosYMenu
     */
    public MetodosYMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mensaje = new javax.swing.JTextField();
        enviar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        imagenLike = new javax.swing.JTextField();
        like = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comentarimagen = new javax.swing.JTextField();
        comentarioimagen = new javax.swing.JTextField();
        comentar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        subirimagen = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        comentariopublica = new javax.swing.JTextField();
        publicar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Escribir mensaje aqui...");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, 50));
        getContentPane().add(mensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 150, -1));

        enviar.setText("ENVIAR");
        enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarActionPerformed(evt);
            }
        });
        getContentPane().add(enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, -1));

        jLabel2.setText("URL de la imagen");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 120, -1));
        getContentPane().add(imagenLike, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 150, -1));

        like.setText("Dar Like");
        like.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                likeActionPerformed(evt);
            }
        });
        getContentPane().add(like, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, -1));

        jLabel3.setText("Comentario");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 90, 20));

        jLabel4.setText("Imagen");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 50, -1));
        getContentPane().add(comentarimagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 110, -1));
        getContentPane().add(comentarioimagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 170, 100, -1));

        comentar.setText("Comentar");
        comentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comentarActionPerformed(evt);
            }
        });
        getContentPane().add(comentar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 90, -1));

        jLabel5.setText("Imagen");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 50, -1));
        getContentPane().add(subirimagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 110, -1));

        jLabel6.setText("Comentario");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 70, -1));
        getContentPane().add(comentariopublica, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 100, -1));

        publicar.setText("Publicar");
        publicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publicarActionPerformed(evt);
            }
        });
        getContentPane().add(publicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
 /**
  * Publica en el muro del usuario por defecto el mensaje que escribimos en el Text Field "mensaje"     
     */
    private void enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarActionPerformed
                ConfigurationBuilder cb = new ConfigurationBuilder();
cb.setDebugEnabled(true)
  .setOAuthAppId("1538426176461550")
  .setOAuthAppSecret("ec2983593488cb1c245d11db2275b45d")
  .setOAuthAccessToken("EAACEdEose0cBAIGIyZBnPmfkF6ZAIVTk4DE0r1uJBhQnYhBBgMicuKHpJVtYliOzV5Us9hNhd5fENGagOzbP2X1ihtlopMWdO6Qqyb5tD1xMZCzGOZBu8zxzjXQMltMckHE8fghHYfecs6gOFuPkbAYPpmmvfk3GtrcHGiWXNAZDZD")
  .setOAuthPermissions("email,publish_stream,...");
FacebookFactory ff = new FacebookFactory(cb.build());
        facebook4j.Facebook facebook = ff.getInstance();
        try {
            facebook.postStatusMessage(mensaje.getText());
        } catch (FacebookException ex) {
            Logger.getLogger(MetodosYMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_enviarActionPerformed
        /**
         * Este Método da un me gusta a la imagen de nuestro muro que hayamos pasado a través de text field "imagenLike"
         * @param evt 
         */
    private void likeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_likeActionPerformed
       ConfigurationBuilder cb = new ConfigurationBuilder();
cb.setDebugEnabled(true)
  .setOAuthAppId("1538426176461550")
  .setOAuthAppSecret("ec2983593488cb1c245d11db2275b45d")
  .setOAuthAccessToken("EAACEdEose0cBAKaehh8ZCD4HD4OUoYZAvL1YYsUTfNak7QDmw09uUQMVFp2ooMRZAhxM4nx5k0ynoKrdjwO40509JrcRidAzPBg7zGdJ2gZB8uJE1xRVXAcup79hd0uL33GUmKo2LFo8uKPVzkiJdFEGxOcPIzN4tJlOVbBQUgZDZD")
  .setOAuthPermissions("email,publish_stream,...");
FacebookFactory ff = new FacebookFactory(cb.build());
        facebook4j.Facebook facebook = ff.getInstance();
        try {
            facebook.likePost(imagenLike.getText());
            System.out.println("like");
        } catch (FacebookException ex) {
            Logger.getLogger(MetodosYMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_likeActionPerformed
    /**
     * Con este metodo puedes dejar un comentario en una imagen de tu muro en facebook
     * @param evt 
     */
    private void comentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comentarActionPerformed
        ConfigurationBuilder cb = new ConfigurationBuilder();
        cb.setDebugEnabled(true)
  .setOAuthAppId("1538426176461550")
  .setOAuthAppSecret("ec2983593488cb1c245d11db2275b45d")
  .setOAuthAccessToken("EAACEdEose0cBAFPxAJoOGhtiV6jwMsNijAooLrlX8PyoU4mTRHvLQ2JzzseJ6KZAHDhTOZCjL7S9NE4yfjhZCRWXdejiuG4ftKcrL5LlrO56TYBfQhiINXLzs02SKb6OQyZCA4MWjlCaUG5jVKVLjxuL72yOn6Dc4RuxXRG4CQZDZD")
  .setOAuthPermissions("email,publish_stream,...");
FacebookFactory ff = new FacebookFactory(cb.build());
facebook4j.Facebook facebook = ff.getInstance();
        try {
            facebook.commentPhoto(comentarimagen.getText(),comentarioimagen.getText());
        } catch (FacebookException ex) {
            Logger.getLogger(MetodosYMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_comentarActionPerformed
       /**
        * Este metodo publica la imagen que quieras pasandole la direccion de esta y le añade un comentario si lo deseas
        * @param evt 
        */
    private void publicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publicarActionPerformed
            ConfigurationBuilder cb = new ConfigurationBuilder();
        cb.setDebugEnabled(true)
  .setOAuthAppId("949180598530284")
  .setOAuthAppSecret("88a4340650a3d5a20a4152a41553f5a4")
  .setOAuthAccessToken("EAACEdEose0cBAIPHkUuLMsSItkSjgfuI5YzUGRTyeuGjW7jbQAdVeamQfp4mAQsf4LguAzJ9YReWdXlaBJIIHCwtE5PIosTYlWqHWjAZBl1JjQfn2v9pkD1v4CwNAuEiZBndtblrxDC5RnWfQf7zr0bZCM484Hbc7FZB04EnAwZDZD")
  .setOAuthPermissions("email,publish_stream,...");
        FacebookFactory ff = new FacebookFactory(cb.build());
facebook4j.Facebook facebook = ff.getInstance();
        try {
            facebook.postLink(new URL(subirimagen.getText()), comentariopublica.getText());
        } catch (MalformedURLException ex) {
            Logger.getLogger(JFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FacebookException ex) {
            Logger.getLogger(JFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_publicarActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MetodosYMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MetodosYMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MetodosYMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MetodosYMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MetodosYMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton comentar;
    private javax.swing.JTextField comentarimagen;
    private javax.swing.JTextField comentarioimagen;
    private javax.swing.JTextField comentariopublica;
    private javax.swing.JButton enviar;
    private javax.swing.JTextField imagenLike;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton like;
    private javax.swing.JTextField mensaje;
    private javax.swing.JButton publicar;
    private javax.swing.JTextField subirimagen;
    // End of variables declaration//GEN-END:variables
}
